package io.git.welldefassio.avaliador.application.exception;

public class DadosClienteNotFoundException extends Exception{

    public DadosClienteNotFoundException() {
        super("Dados cliente n√£o encontrado para cpf informado");
    }
}
